version: "3.4"
services:
  server:
    image: jefarr/k8s_sandbox_server:latest
    build:
      context: ./server
      dockerfile: Dockerfile
  client:
    image: jefarr/k8s_sandbox_client:latest
    build:
      context: ./client
      dockerfile: Dockerfile
